




# ---------------BUILD---------------------
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
# create folder called src which the build will be put into.
WORKDIR /src
# Grab everything from top level directory.
COPY . .
#Create subfolder.
WORKDIR /src/WebApi
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish
# -o = output = /app/publish/WebApi.dll
# -c = config: Release

# -------------RUNTIME---------------
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

ENV ASPNETCORE_ENVIRONMENT=Development

COPY --from=build /app/publish .

ENTRYPOINT [ "dotnet", "WebApi.dll" ]

# Summary:
# Your source code
#       ↓
# COPY into build environment
#       ↓
# dotnet restore
#       ↓
# Get dependencies
#       ↓
# dotnet publish
#       ↓
# Compile + produce WebApi.dll
#       ↓
# Copy published files into runtime image
#       ↓
# WHEN [user] Starts container
#       ↓
# dotnet WebApi.dll
