




# ---------------BUILD---------------------
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
# create folder called src which the build will be put into.
WORKDIR /src
# Grab everything from top level directory.
COPY . .
#Create subfolder.
WORKDIR /src/WebApi
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish
# /app/publish/TaskService.Api.dll

# -------------RUNTIME---------------
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT [ "dotnet", "WebApi.dll" ]
